export interface Dialogue {
  id: number;
  speaker: 'Coach' | 'Star Player' | 'Rookie' | 'Fan' | 'Referee' | 'Commentator' | 'Opponent' | 'Mascot';
  text: string;
}

export const DialogueDatabase: Dialogue[] = [
  { id: 1, speaker: 'Coach', text: '听着，伙计们，第四节了，我们必须打出侵略性！防守，防守，再防守！' },
  { id: 2, speaker: 'Star Player', text: '把球给我，教练。是时候终结比赛了。' },
  { id: 3, speaker: 'Rookie', text: '我的腿有点软，但我会尽力跟上节奏的。' },
  { id: 4, speaker: 'Fan', text: '快投啊！你站那么远干什么？' },
  { id: 5, speaker: 'Referee', text: '走步！球权转换。' },
  { id: 6, speaker: 'Commentator', text: '难以置信的传球！他简直长了后眼！' },
  { id: 7, speaker: 'Opponent', text: '别想在我头上得分，菜鸟。' },
  { id: 8, speaker: 'Mascot', text: '（跳舞）来吧，噪音再大一点！' },
  { id: 9, speaker: 'Coach', text: '暂停！都过来！我们跑一个“三角进攻”战术。' },
  { id: 10, speaker: 'Star Player', text: '我感觉今天手感火热，每个投篮都像训练一样轻松。' },
  { id: 11, speaker: 'Rookie', text: '我刚才那个抢断怎么样？我练习了好久！' },
  { id: 12, speaker: 'Fan', text: '这裁判是瞎了吗？那绝对是犯规！' },
  { id: 13, speaker: 'Referee', text: '技术犯规！对替补席的抱怨。' },
  { id: 14, speaker: 'Commentator', text: '三分线外一步！命中！这是超远距离的导弹！' },
  { id: 15, speaker: 'Opponent', text: '你防不住我，我能从左边过你一百次。' },
  { id: 16, speaker: 'Mascot', text: '（做俯卧撑）为了胜利，我能做到一千个！' },
  { id: 17, speaker: 'Coach', text: '记住我们的口号：没有轻松的得分！' },
  { id: 18, speaker: 'Star Player', text: '我的膝盖有点不舒服，但我可以坚持。' },
  { id: 19, speaker: 'Rookie', text: '我终于在NBA得分了！这感觉太棒了！' },
  { id: 20, speaker: 'Fan', text: '我要退票！这打得是什么玩意儿！' },
  { id: 21, speaker: 'Referee', text: '恶意犯规！请离场。' },
  { id: 22, speaker: 'Commentator', text: '他像一阵风一样突破了防线，然后是标志性的扣篮！' },
  { id: 23, speaker: 'Opponent', text: '我们必须加强篮板球，不能给他们二次进攻的机会。' },
  { id: 24, speaker: 'Mascot', text: '（给球迷击掌）谢谢你们的支持！' },
  { id: 25, speaker: 'Coach', text: '中场休息时，我们调整一下防守策略。' },
  { id: 26, speaker: 'Star Player', text: '我需要更多的无球掩护，他们一直在包夹我。' },
  { id: 27, speaker: 'Rookie', text: '教练，我能再多打几分钟吗？我感觉状态正佳。' },
  { id: 28, speaker: 'Fan', text: '把那个大个子换下去！他跑不动了！' },
  { id: 29, speaker: 'Referee', text: '防守三秒违例！' },
  { id: 30, speaker: 'Commentator', text: '他用一个漂亮的欧洲步晃过了所有人！' },
  { id: 31, speaker: 'Opponent', text: '我们必须把比分追回来，时间还够！' },
  { id: 32, speaker: 'Mascot', text: '（扔T恤）免费的T恤！快来抢！' },
  { id: 33, speaker: 'Coach', text: '罚球线上的表现太差了，赛后加练！' },
  { id: 34, speaker: 'Star Player', text: '我不在乎数据，我只在乎胜利。' },
  { id: 35, speaker: 'Rookie', text: '我得向老将们学习，他们的经验太宝贵了。' },
  { id: 36, speaker: 'Fan', text: 'MVP！MVP！' },
  { id: 37, speaker: 'Referee', text: '进攻犯规！推人。' },
  { id: 38, speaker: 'Commentator', text: '比赛进入了白热化，双方比分交替上升！' },
  { id: 39, speaker: 'Opponent', text: '别灰心，我们还有机会，保持冷静！' },
  { id: 40, speaker: 'Mascot', text: '（做扣篮动作）我也能扣篮！只是篮筐太高了！' },
  { id: 41, speaker: 'Coach', text: '把球传给空位的人，不要粘球！' },
  { id: 42, speaker: 'Star Player', text: '我的脚踝扭了一下，但问题不大。' },
  { id: 43, speaker: 'Rookie', text: '我得提高我的投篮命中率，不能浪费机会。' },
  { id: 44, speaker: 'Fan', text: '我们是冠军！我们是最棒的！' },
  { id: 45, speaker: 'Referee', text: '争球！双方跳球。' },
  { id: 46, speaker: 'Commentator', text: '他用一个后撤步跳投，完美地避开了防守！' },
  { id: 47, speaker: 'Opponent', text: '他们的联防让我们很难受，必须找到突破口。' },
  { id: 48, speaker: 'Mascot', text: '（做鬼脸）嘘！让对手安静下来！' },
  { id: 49, speaker: 'Coach', text: '下一回合，全场紧逼！给他们压力！' },
  { id: 50, speaker: 'Star Player', text: '我需要一个冰敷袋，赛后见。' },
  { id: 51, speaker: 'Rookie', text: '我感觉我能防住任何人，我的速度是优势。' },
  { id: 52, speaker: 'Fan', text: '我们远道而来，就是为了看一场胜利！' },
  { id: 53, speaker: 'Referee', text: '出界！球权属于红队。' },
  { id: 54, speaker: 'Commentator', text: '这不仅仅是一场比赛，这是意志的较量！' },
  { id: 55, speaker: 'Opponent', text: '我们不能让他们打出快攻，回防要快！' },
  { id: 56, speaker: 'Mascot', text: '（做啦啦队动作）加油！加油！' },
  { id: 57, speaker: 'Coach', text: '我们必须在内线得分，利用我们的身高优势。' },
  { id: 58, speaker: 'Star Player', text: '我得练习我的左手运球，这是我的弱点。' },
  { id: 59, speaker: 'Rookie', text: '我梦想着有一天能像他一样，成为全明星。' },
  { id: 60, speaker: 'Fan', text: '再来一个三分！我请你喝啤酒！' },
  { id: 61, speaker: 'Referee', text: '暂停！有球员受伤。' },
  { id: 62, speaker: 'Commentator', text: '他用一个假动作骗过了防守，然后轻松上篮！' },
  { id: 63, speaker: 'Opponent', text: '我们必须把节奏慢下来，打阵地战。' },
  { id: 64, speaker: 'Mascot', text: '（做俯卧撑）为了胜利，我能做到一千个！' },
  { id: 65, speaker: 'Coach', text: '我们必须相信彼此，打出团队篮球。' },
  { id: 66, speaker: 'Star Player', text: '我今天的手感糟透了，但我会用防守弥补。' },
  { id: 67, speaker: 'Rookie', text: '我得感谢教练给我这个机会，我不会让他失望的。' },
  { id: 68, speaker: 'Fan', text: '把球传给那个穿23号的！' },
  { id: 69, speaker: 'Referee', text: '阻挡犯规！' },
  { id: 70, speaker: 'Commentator', text: '他像一个魔术师一样，把球传到了不可思议的位置！' },
  { id: 71, speaker: 'Opponent', text: '我们不能再失误了，每一个球权都很重要。' },
  { id: 72, speaker: 'Mascot', text: '（做滑稽的动作）让大家笑一笑！' },
  { id: 73, speaker: 'Coach', text: '记住，胜利属于最渴望它的人！' },
  { id: 74, speaker: 'Star Player', text: '我需要休息一下，我的体能快耗尽了。' },
  { id: 75, speaker: 'Rookie', text: '我得提高我的力量，这样才能在内线对抗。' },
  { id: 76, speaker: 'Fan', text: '我爱死这个球馆的气氛了！' },
  { id: 77, speaker: 'Referee', text: '延误比赛！警告一次。' },
  { id: 78, speaker: 'Commentator', text: '他用一个不可思议的拉杆上篮，完成了2+1！' },
  { id: 79, speaker: 'Opponent', text: '我们必须限制他的得分，他是他们的核心。' },
  { id: 80, speaker: 'Mascot', text: '（做后空翻）看我的！' },
  { id: 81, speaker: 'Coach', text: '我们现在领先，但不能放松警惕！' },
  { id: 82, speaker: 'Star Player', text: '我的目标是总冠军，不是个人荣誉。' },
  { id: 83, speaker: 'Rookie', text: '我得学习如何更好地阅读防守。' },
  { id: 84, speaker: 'Fan', text: '再来一个！再来一个！' },
  { id: 85, speaker: 'Referee', text: '进攻三秒违例！' },
  { id: 86, speaker: 'Commentator', text: '他像一个老将一样冷静，命中了关键罚球！' },
  { id: 87, speaker: 'Opponent', text: '我们必须打得更聪明，而不是更努力。' },
  { id: 88, speaker: 'Mascot', text: '（和小孩合影）微笑！茄子！' },
  { id: 89, speaker: 'Coach', text: '下半场开始，我们要打得更有侵略性！' },
  { id: 90, speaker: 'Star Player', text: '我得在防守端做得更好，不能让对手轻松得分。' },
  { id: 91, speaker: 'Rookie', text: '我得适应NBA的强度，这比大学联赛难多了。' },
  { id: 92, speaker: 'Fan', text: '把球给我，我来投！' },
  { id: 93, speaker: 'Referee', text: '界外球！' },
  { id: 94, speaker: 'Commentator', text: '他用一个漂亮的转身跳投，让防守人无能为力！' },
  { id: 95, speaker: 'Opponent', text: '我们必须把节奏提起来，打乱他们的部署。' },
  { id: 96, speaker: 'Mascot', text: '（假装哭泣）裁判不公平！' },
  { id: 97, speaker: 'Coach', text: '我们必须保护好篮板，这是胜利的关键！' },
  { id: 98, speaker: 'Star Player', text: '我得在关键时刻站出来，这是我的责任。' },
  { id: 99, speaker: 'Rookie', text: '我得学习如何更好地利用我的身体。' },
  { id: 100, speaker: 'Fan', text: '我们是不可战胜的！' },
  { id: 101, speaker: 'Coach', text: '快攻！快攻！不要给他们回防的机会！' },
  { id: 102, speaker: 'Star Player', text: '我的传球视野是我的优势，我能找到空位队友。' },
  { id: 103, speaker: 'Rookie', text: '我得在训练中更加努力，才能争取到更多上场时间。' },
  { id: 104, speaker: 'Fan', text: '嘘声！给他们点颜色看看！' },
  { id: 105, speaker: 'Referee', text: '假摔！警告。' },
  { id: 106, speaker: 'Commentator', text: '比赛还剩最后五秒，一球定胜负！' },
  { id: 107, speaker: 'Opponent', text: '我们必须防住最后一投，不能让他们轻松出手！' },
  { id: 108, speaker: 'Mascot', text: '（紧张地抱头）哦，天哪，太刺激了！' },
  { id: 109, speaker: 'Coach', text: '打得漂亮！这就是团队合作的力量！' },
  { id: 110, speaker: 'Star Player', text: '我得去接受治疗，今晚打得太拼了。' },
  { id: 111, speaker: 'Rookie', text: '我从这场比赛中学到了很多，受益匪浅。' },
  { id: 112, speaker: 'Fan', text: '我们赢了！派对时间！' },
  { id: 113, speaker: 'Referee', text: '比赛结束！比分是105比103。' },
  { id: 114, speaker: 'Commentator', text: '这是一场史诗般的对决，载入史册的比赛！' },
  { id: 115, speaker: 'Opponent', text: '我们输了，但我们战斗到了最后一刻，下次我们会赢回来。' },
  { id: 116, speaker: 'Mascot', text: '（庆祝）胜利属于我们！' },
  { id: 117, speaker: 'Coach', text: '明天早上六点，训练馆见！' },
  { id: 118, speaker: 'Star Player', text: '我得给我的孩子们打电话，告诉他们我赢了。' },
  { id: 119, speaker: 'Rookie', text: '我得感谢我的父母，他们一直支持我。' },
  { id: 120, speaker: 'Fan', text: '我要买一件他的球衣！' },
  { id: 121, speaker: 'Coach', text: '注意跑位，不要站在原地看球！' },
  { id: 122, speaker: 'Star Player', text: '我得保持我的状态，不能松懈。' },
  { id: 123, speaker: 'Rookie', text: '我得学习如何更好地控制我的情绪。' },
  { id: 124, speaker: 'Fan', text: '再来一个空接！' },
  { id: 125, speaker: 'Referee', text: '非法掩护！' },
  { id: 126, speaker: 'Commentator', text: '他像一个艺术家一样，在空中完成了动作！' },
  { id: 127, speaker: 'Opponent', text: '我们必须限制他们的三分球，他们太准了。' },
  { id: 128, speaker: 'Mascot', text: '（做投篮动作）三分命中！' },
  { id: 129, speaker: 'Coach', text: '我们必须打出侵略性，但要保持冷静。' },
  { id: 130, speaker: 'Star Player', text: '我得练习我的后仰跳投，这是我的杀手锏。' },
  { id: 131, speaker: 'Rookie', text: '我得学习如何更好地与队友沟通。' },
  { id: 132, speaker: 'Fan', text: '这是我见过的最精彩的比赛！' },
  { id: 133, speaker: 'Referee', text: '防守犯规！打手。' },
  { id: 134, speaker: 'Commentator', text: '他用一个漂亮的盖帽，拒绝了对手的得分！' },
  { id: 135, speaker: 'Opponent', text: '我们必须打出我们的风格，不要被他们带偏。' },
  { id: 136, speaker: 'Mascot', text: '（模仿裁判）走步！' },
  { id: 137, speaker: 'Coach', text: '我们必须在细节上做得更好，细节决定成败。' },
  { id: 138, speaker: 'Star Player', text: '我得去健身房，增强我的核心力量。' },
  { id: 139, speaker: 'Rookie', text: '我得学习如何更好地保护球。' },
  { id: 140, speaker: 'Fan', text: '我今天嗓子都喊哑了！' },
  { id: 141, speaker: 'Referee', text: '双方犯规抵消！' },
  { id: 142, speaker: 'Commentator', text: '他用一个漂亮的背后运球，晃过了防守人！' },
  { id: 143, speaker: 'Opponent', text: '我们必须在篮下得分，不能只依靠外线。' },
  { id: 144, speaker: 'Mascot', text: '（做鬼脸）嘘！让对手安静下来！' },
  { id: 145, speaker: 'Coach', text: '我们必须打出我们的速度，用速度压垮他们。' },
  { id: 146, speaker: 'Star Player', text: '我得练习我的急停跳投，这是我的得分利器。' },
  { id: 147, speaker: 'Rookie', text: '我得学习如何更好地利用我的脚步。' },
  { id: 148, speaker: 'Fan', text: '再来一个三分！我请你喝啤酒！' },
  { id: 149, speaker: 'Referee', text: '投篮犯规！两次罚球。' },
  { id: 150, speaker: 'Commentator', text: '他用一个漂亮的转身，完成了高难度上篮！' },
  { id: 151, speaker: 'Opponent', text: '我们必须把比分追回来，时间还够！' },
  { id: 152, speaker: 'Mascot', text: '（扔T恤）免费的T恤！快来抢！' },
  { id: 153, speaker: 'Coach', text: '我们必须打出我们的防守，让他们感到窒息。' },
  { id: 154, speaker: 'Star Player', text: '我得练习我的假动作，这样才能更好地突破。' },
  { id: 155, speaker: 'Rookie', text: '我得学习如何更好地阅读比赛。' },
  { id: 156, speaker: 'Fan', text: 'MVP！MVP！' },
  { id: 157, speaker: 'Referee', text: '技术犯规！对教练的抱怨。' },
  { id: 158, speaker: 'Commentator', text: '他像一个老将一样冷静，命中了关键三分！' },
  { id: 159, speaker: 'Opponent', text: '我们必须打得更聪明，而不是更努力。' },
  { id: 160, speaker: 'Mascot', text: '（做扣篮动作）我也能扣篮！只是篮筐太高了！' },
  { id: 161, speaker: 'Coach', text: '我们必须保护好篮板，这是胜利的关键！' },
  { id: 162, speaker: 'Star Player', text: '我得在关键时刻站出来，这是我的责任。' },
  { id: 163, speaker: 'Rookie', text: '我得学习如何更好地利用我的身体。' },
  { id: 164, speaker: 'Fan', text: '我们是不可战胜的！' },
  { id: 165, speaker: 'Referee', text: '争球！双方跳球。' },
  { id: 166, speaker: 'Commentator', text: '他用一个后撤步跳投，完美地避开了防守！' },
  { id: 167, speaker: 'Opponent', text: '他们的联防让我们很难受，必须找到突破口。' },
  { id: 168, speaker: 'Mascot', text: '（做鬼脸）嘘！让对手安静下来！' },
  { id: 169, speaker: 'Coach', text: '下一回合，全场紧逼！给他们压力！' },
  { id: 170, speaker: 'Star Player', text: '我需要一个冰敷袋，赛后见。' },
  { id: 171, speaker: 'Rookie', text: '我感觉我能防住任何人，我的速度是优势。' },
  { id: 172, speaker: 'Fan', text: '我们远道而来，就是为了看一场胜利！' },
  { id: 173, speaker: 'Referee', text: '出界！球权属于红队。' },
  { id: 174, speaker: 'Commentator', text: '这不仅仅是一场比赛，这是意志的较量！' },
  { id: 175, speaker: 'Opponent', text: '我们不能让他们打出快攻，回防要快！' },
  { id: 176, speaker: 'Mascot', text: '（做啦啦队动作）加油！加油！' },
  { id: 177, speaker: 'Coach', text: '我们必须在内线得分，利用我们的身高优势。' },
  { id: 178, speaker: 'Star Player', text: '我得练习我的左手运球，这是我的弱点。' },
  { id: 179, speaker: 'Rookie', text: '我梦想着有一天能像他一样，成为全明星。' },
  { id: 180, speaker: 'Fan', text: '再来一个三分！我请你喝啤酒！' },
  { id: 181, speaker: 'Referee', text: '暂停！有球员受伤。' },
  { id: 182, speaker: 'Commentator', text: '他用一个假动作骗过了防守，然后轻松上篮！' },
  { id: 183, speaker: 'Opponent', text: '我们必须把节奏慢下来，打阵地战。' },
  { id: 184, speaker: 'Mascot', text: '（做俯卧撑）为了胜利，我能做到一千个！' },
  { id: 185, speaker: 'Coach', text: '我们必须相信彼此，打出团队篮球。' },
  { id: 186, speaker: 'Star Player', text: '我今天的手感糟透了，但我会用防守弥补。' },
  { id: 187, speaker: 'Rookie', text: '我得感谢教练给我这个机会，我不会让他失望的。' },
  { id: 188, speaker: 'Fan', text: '把球传给那个穿23号的！' },
  { id: 189, speaker: 'Referee', text: '阻挡犯规！' },
  { id: 190, speaker: 'Commentator', text: '他像一个魔术师一样，把球传到了不可思议的位置！' },
  { id: 191, speaker: 'Opponent', text: '我们不能再失误了，每一个球权都很重要。' },
  { id: 192, speaker: 'Mascot', text: '（做滑稽的动作）让大家笑一笑！' },
  { id: 193, speaker: 'Coach', text: '记住，胜利属于最渴望它的人！' },
  { id: 194, speaker: 'Star Player', text: '我需要休息一下，我的体能快耗尽了。' },
  { id: 195, speaker: 'Rookie', text: '我得提高我的力量，这样才能在内线对抗。' },
  { id: 196, speaker: 'Fan', text: '我爱死这个球馆的气氛了！' },
  { id: 197, speaker: 'Referee', text: '延误比赛！警告一次。' },
  { id: 198, speaker: 'Commentator', text: '他用一个不可思议的拉杆上篮，完成了2+1！' },
  { id: 199, speaker: 'Opponent', text: '我们必须限制他的得分，他是他们的核心。' },
  { id: 200, speaker: 'Mascot', text: '（做后空翻）看我的！' },
];
